### ISSUE TITLE
add my NRO 45 m CMZ CS(2-1) cube to the list of data sets available on the CMZ.

### ISSUE THREAD

**Issue by pyhsiehATalma** [CentralMolecularZone/DataSets#11]
I would like to add my NRO 45 m CMZ CS(2-1) cube to the list of data sets available on the CMZ.
The FITS can be found in zenodo.
https://zenodo.org/record/7708322#.ZAiKsnZBy5c

**Comment by keflavich** [comment]
@pyhsiehATalma could you make a pull request?  Just add a new line to the appropriate section in https://github.com/CentralMolecularZone/DataSets/blob/master/README.md

**Comment by pyhsiehATalma** [comment]
Thanks. I have made the pull request.

**Comment by keflavich** [comment]
Thanks!
